# Generated by Django 4.2.23 on 2025-07-04 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0003_comment_image_reply_image_alter_reply_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('problem', models.TextField()),
                ('solution', models.TextField()),
                ('effect', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('liked', models.ManyToManyField(related_name='liked_proposal_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProposalReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_replies', to='proposals.proposalcomment')),
                ('liked', models.ManyToManyField(related_name='liked_proposal_reply', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProposalPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('question', models.TextField()),
                ('result_choice', models.CharField(max_length=100)),
                ('result_percent', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('community_post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_post', to='community.post')),
                ('liked', models.ManyToManyField(related_name='liked_proposal_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='proposalcomment',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_comments', to='proposals.proposalpost'),
        ),
        migrations.AddField(
            model_name='proposalcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
