# Generated by Django 4.2.23 on 2025-07-04 21:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalpost',
            name='scrapped',
            field=models.ManyToManyField(blank=True, related_name='scrapped_proposal_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
