# Generated by Django 4.2.23 on 2025-07-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_proposalpost_scrapped'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalcomment',
            name='link_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
