# Generated by Django 4.2.23 on 2025-07-05 19:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proposals', '0003_proposalcomment_link_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalpost',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='liked_proposal_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
