# Generated by Django 4.2.23 on 2025-07-09 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0004_alter_proposalpost_liked'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalReplyEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('link1', models.URLField(blank=True, max_length=500, null=True)),
                ('link2', models.URLField(blank=True, max_length=500, null=True)),
                ('link3', models.URLField(blank=True, max_length=500, null=True)),
                ('link4', models.URLField(blank=True, max_length=500, null=True)),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_reply_evidence', to='proposals.proposalreply')),
            ],
        ),
    ]
