# Generated by Django 4.2.23 on 2025-07-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='finish_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
