# Generated by Django 4.2.23 on 2025-07-05 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_comment_image_reply_image_alter_reply_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('evidence', models.URLField(blank=True, max_length=500, null=True)),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_evidence', to='community.reply')),
            ],
        ),
        migrations.CreateModel(
            name='CommentEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('evidence', models.URLField(blank=True, max_length=500, null=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_evidence', to='community.comment')),
            ],
        ),
    ]
