# Generated by Django 4.2.23 on 2025-07-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_alter_comment_created_at_alter_reply_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='filtered_comments',
            field=models.IntegerField(default=0),
        ),
    ]
