# Generated by Django 4.2.23 on 2025-07-05 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_post_filtered_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='filtered_comments',
        ),
    ]
