# Generated by Django 4.2.23 on 2025-07-06 10:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0007_remove_post_filtered_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='scrapped',
            field=models.ManyToManyField(blank=True, related_name='scrapped_community_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
