# Generated by Django 4.2.23 on 2025-07-06 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_scrapped'),
        ('community', '0008_post_scrapped'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='related_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_posts', to='articles.article'),
        ),
    ]
