# Generated by Django 4.2.23 on 2025-07-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_post_related_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentevidence',
            old_name='evidence',
            new_name='link1',
        ),
        migrations.AddField(
            model_name='commentevidence',
            name='link2',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
