# Generated by Django 4.2.23 on 2025-07-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0010_rename_evidence_commentevidence_link1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentevidence',
            name='link3',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='commentevidence',
            name='link4',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
