# Generated by Django 4.2.23 on 2025-07-09 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0011_commentevidence_link3_commentevidence_link4'),
    ]

    operations = [
        migrations.RenameField(
            model_name='replyevidence',
            old_name='evidence',
            new_name='link1',
        ),
        migrations.AddField(
            model_name='replyevidence',
            name='link2',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='replyevidence',
            name='link3',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='replyevidence',
            name='link4',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
