# Generated by Django 4.2.23 on 2025-07-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0012_rename_evidence_replyevidence_link1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='community/'),
        ),
    ]
