# Generated by Django 4.2.23 on 2025-07-06 10:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0002_articlecomment_articlereply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='scrapped',
            field=models.ManyToManyField(blank=True, related_name='scrapped_article_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
