# Generated by Django 4.2.23 on 2025-07-09 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_scrapped'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleReplyEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('link1', models.URLField(blank=True, max_length=500, null=True)),
                ('link2', models.URLField(blank=True, max_length=500, null=True)),
                ('link3', models.URLField(blank=True, max_length=500, null=True)),
                ('link4', models.URLField(blank=True, max_length=500, null=True)),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_reply_evidence', to='articles.articlereply')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleCommentEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('link1', models.URLField(blank=True, max_length=500, null=True)),
                ('link2', models.URLField(blank=True, max_length=500, null=True)),
                ('link3', models.URLField(blank=True, max_length=500, null=True)),
                ('link4', models.URLField(blank=True, max_length=500, null=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_comment_evidence', to='articles.articlecomment')),
            ],
        ),
    ]
